#!/bin/bash
# ntwk2001_encrypt
# Created by Marcus Dyck 20 Nov 2014
# This script handles all the encryption and decription for the files included in the NTWK-2001 project
# Exit codes:
# 1: Nothin' yet
# Last modified on 20 Nov 2014

# Syntax:
# encrypt [string] [keyfile]: encrypts the contents of the argument passed using the key provided.
# decrypt [string] [keyfile]: same thing as encrypt, but the other way around.
# checksum [file]: Calculates the sha512 hash for the specific file.

function encrypt() {
    result=`echo "$1" | openssl enc -aes-256-cbc -pass file:$2`
}

function decrypt() {
    result=`echo "$1" | openssl enc -d -aes-256-cbc -pass file:$2`
}

function checksum() {
    checksum=`sha512sum $1`
}
