#!/bin/bash
# ntwk2001_encrypt
# Created by Marcus Dyck 20 Nov 2014
# This script handles all the encryption and decription for the files included in the NTWK-2001 project
# Last modified on 24 Nov 2014

# Syntax:
# encrypt [string] [keyfile]: encrypts the contents of the argument passed using the key provided.
# decrypt [string] [keyfile]: same thing as encrypt, but the other way around.
# checksum [file]: Calculates the sha512 hash for the specific file.

function encrypt() {
    openssl enc -aes-256-cbc -pass file:"/etc/sysconfig/bash_file_monitor"
}

function decrypt() {
    openssl enc -d -aes-256-cbc -pass file:"/etc/sysconfig/bash_file_monitor"
}

function checksum() {
    sha512sum
}
