#!/bin/bash
# project_setup
# Created by Marcus Dyck 18 Oct 2014
# This script installs and removes all the files for the NTWK-2001 scripting project
# Exit codes:
# 1: No/Wrong arguments specified
# 2: Script was not run as root
# 3: "No" was specified when prompted to continue with install/removal
# Last modified on 20 Nov 2014

# Useful variables:
# confirmed (bool): Created by the confirm function and says whether the user decided to continue from the last prompt. (answered yes=true)

# Does the entire "are you sure?" process. Exits with code 2 if "N" is specified
function confirm() {
    repeat=true
    while $repeat
    do
        echo -n "Do you wish to continue? (y/n): "
        read answer
        # Credit to https://stackoverflow.com/questions/2264428/converting-string-to-lower-case-in-bash-shell-scripting
        answer=`echo $answer | tr '[:upper:]' '[:lower:]'` # Makes the result lower case
        if [ -z $answer ]
        then
            echo "Please enter y or n."
            repeat=true
        else
            if [ $answer == "y" ]
            then
                confirmed=true
                repeat=false
            elif [ $answer == "n" ]
            then
                exit 3
                confirmed=false
                repeat=false
            else
                echo "Please enter y or n."
                repeat=true
            fi
        fi
    done
}

# Prompts the user for a value.
# Syntax: prompt_value [question] [default value]
# Returns the variable "result"
function prompt_value() {
    echo -n $1 "[default: $2]: "
    read result
    if [ -z $result ]
    then
        echo "Using the default of $2"
        result=$3
    fi
}

# Show usage info if no argument is specified
if [ -z $@ ]
then
    echo 'Usage: project_setup {install|uninstall}'
    exit 1
fi

# Make sure only root can run the install script
# Credit to http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 2
fi

# Install argument handler
if [ $1 = "install" ]
then
    echo "This program will now create a configuration file and install"
    echo "the components of Marcus Dyck's scripting project into the"
    echo "specified locations."
    confirmed=confirm
    if $confirmed
    then
        echo "Installing..."
        # Prompt for various installation values
        prompt_value "Enter an admin email address" "root@localhost"
        email=$result
        prompt_value "Specifiy the installation directory" "/usr/bin/"
        install_directory=$result
        prompt_value "Specify the location for the checksums" "/var/lib/ntwk2001"
        checksum_directory=$result
        prompt_value "Specify the location for the file backups" "/var/lib/ntwk2001/backups"
        backup_directory=$result
        prompt_value "Specify the frequency of file scans (in seconds)" "600"
        scan_freq=$result
        
        #Do all the installation work DO NOT FORGET TO DO THIS!
        # Move the config file to /etc/myproject_config (this cannot be changed)
        
        
    fi
    
fi

# Uninstall argument handler
if [ $1 = "uninstall" ]
then
    echo "This program will now uninstall Marcus Dyck\'s scripting project."
    confirmed=`confirm`
    if $confirmed
    then
        echo "Removing..."
         # ADD ALL THIS AS WELL
    fi
fi
